class alerts:
    URL = "https://demoqa.com/alerts"
    boton1 = "//button[contains(@id,'alertButton')]"
    boton2 = "//button[contains(@id,'timerAlertButton')]"
    boton3 = "//button[contains(@id,'confirmButton')]"
    boton4 = "//button[contains(@id,'promtButton')]"
    text_expected1 = "You clicked a button"
    text_expected2 = "This alert appeared after 5 seconds"
    text_expected_ok = "You selected Ok"
    text_expected_cancel = "You selected Cancel"
    text_expected_prompt = "You entered prueba"
    text_prompt = "prueba"
    confirm_result = "//*[@id='confirmResult']"
    prompt_result = "//*[@id='promptResult']"
